# Site settings
name: Rhythm Patel
title: Rhythm Patel | Software Engineer
description: a CS grad at ASU and software engineer motivated to build performant and high-impact software and user experiences
baseurl: /
url: rhythm-3099.github.io
email: patelrhythmr@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://drive.google.com/drive/folders/1iZuNRwolzOF2uAvfskm6W2_tfheJSAaw
social:
  - title: email
    url: mailto:patelrhythmr@gmail.com
  - title: github
    url: https://github.com/rhythm-3099
  - title: linkedin
    url: https://www.linkedin.com/in/rhythm-3099/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
