# Site settings
name: Brittany Chiang
title: Brittany Chiang | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://bchiang7.github.io/
baseurl: ''
email: brittany.chiang@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://drive.google.com/drive/folders/1iZuNRwolzOF2uAvfskm6W2_tfheJSAaw
social:
  - title: email
    url: mailto:patelrhythmr@gmail.com
  - title: github
    url: https://github.com/rhythm-3099
  - title: linkedin
    url: https://www.linkedin.com/in/rhythm-3099/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
